site_name: 厦门大学·RoboMaster·技术讲座<img src='https://cdn.img.wenhairu.com/images/2020/10/11/CksbD.png'>
site_favicon: favicon.ico
nav:
- RM2020:
    - 雷达全场定位: radar-location.md
    - 电机基本知识: motor-basic-knowledge.md
    - 超级电容同步BUCK电路参数的计算: super-capacitor-sync-buck-calculation.md
    - 可解释的CNN: interpretable-CNN.md
    - 步兵上的姿态控制: infantry-posture-control.md
    - 硬件标准化与系统设计: HWSD-and-system-design.md
    - 有限元分析基础: fundamentals-of-FEA.md
    - μCOSⅢ多任务系统介绍: ucosⅢ-introduction.md
    - 人机工程分析: ergonomic-analysis.md
    - YOLOv3从理论到实践: YOLOv3-theory-to-practice.md
- RM2021:
    - Remain to be organized: index.md
theme: readthedocs
site_author: Crash
copyright: Copyright © 2020 ASR-Crash, maintained by XMU-ROBOT Operation Group