site_name: 厦门大学·RoboMaster·技术讲座<img src='https://cdn.img.wenhairu.com/images/2020/10/11/CksbD.png'>
site_favicon: favicon.ico
nav:
- RM2020:
    - 雷达全场定位: radar-location.md

theme: readthedocs
site_author: Crash
copyright: Copyright © 2020 ASR-Crash, maintained by XMU-ROBOT Operation Group